cloud:
  aws:
    credentials:
      accessKey: AKIATAEGQITMTCKKWZS7
      secretKey: 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
    s3:
      bucket: imagebucket606
    region:
      static: ap-northeast-2
    stack:
      auto: false