# 프로젝트 서버 URL 및 포트 설정
server.url: http://localhost
ta.port: 8083
search.port: 8084
sc.port: 8085
ans.port: 8086

# 서버 설정
server:
  port: 8082
  servlet:
    context-path: /business
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# S3 설정
cloud:
  aws:
    credentials:
      accessKey: AKIATAEGQITM4DIXMJIL
      secretKey: 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
    s3:
      bucket: imagebucket606
    region:
      static: ap-northeast-2
    stack:
      auto: false


# DB 설정
spring:
  #   driver-cl
  # datasource:ass-name: org.mariadb.jdbc.Driver
  #   url: jdbc:mariadb://localhost:3306/checkchaeck?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  #   username: root
  #   password: ssafy

  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#      settings:
#        web-allow-others: true
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver  # Database를 MariaDB로 사용하겠다.
    url: jdbc:mariadb://j9a606.p.ssafy.io/checkchaeck  # MariaDB로 접속 정보
    username: root  # MariaDB로 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: ash0906! # MariaDB로 접속 시 입력할 password 정보 (원하는 것으로 입력)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000
    show-sql: true

# Swagger 설정
springdoc:
  packages-to-scan: com.cc.domain.business.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha