# Generated by Django 4.2.5 on 2023-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_status', models.CharField(default='Unknown', max_length=10)),
                ('image_title', models.CharField(default='Unknown', max_length=100)),
                ('image_publisher', models.CharField(default='Unknown', max_length=100)),
                ('image_author', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
