# Generated by Django 4.2.5 on 2023-09-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_status',
            name='image_price',
            field=models.IntegerField(default=0),
        ),
    ]
